spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
server.port: 8090
mybatis:
  mapper-locations: /mybatis/*.xml
  config-location: classpath:/config/mybatis-config.xml